global:
  resolve_timeout: 5m
  smtp_from: 'hashmimdniyaz@gmail.com'
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_auth_username: 'hashmimdniyaz@gmail.com'
  smtp_auth_password: 'mtqobzrwneayturw'
  smtp_auth_identity: 'hashmimdniyaz@gmail.com'
  smtp_require_tls: true

templates:
- '/etc/alertmanager/*.tmpl'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'hashmimdniyaz@gmail.com'
    headers:
      subject: '{{ template "email.subject" . }}'
    html: '{{ template "email.html" . }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname']