version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - test-network

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9323:9323"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - METRICS_PORT=9323
      - NODE_ENV=production
    networks:
      - test-network
    depends_on:
      - prometheus

networks:
  test-network:
    name: test-network