version: '3.8'

services:
  jenkins:
    environment:
      - JENKINS_USER=${JENKINS_USER:-admin}
      - JENKINS_TOKEN=${JENKINS_TOKEN:-admin}
      - JENKINS_OPTS=--httpPort=8080
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Dhudson.model.UsageStatistics.disabled=true -Djenkins.prometheus.metricspath=/metrics -Djenkins.prometheus.namespace=jenkins -Djenkins.prometheus.defaultDateFormat=
      - PROMETHEUS_GLOBAL_ON=true
      - METRICS_PORT=8080
    ports:
      - "9323:9323"

  prometheus:
    environment:
      - JENKINS_USER=${JENKINS_USER:-admin}
      - JENKINS_TOKEN=${JENKINS_TOKEN:-admin}