version: '3.8'

services:
  jenkins:
    environment:
      - JENKINS_USER=${JENKINS_USER:-admin}
      - JENKINS_TOKEN=${JENKINS_TOKEN:-admin}
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Dhudson.model.UsageStatistics.disabled=true -Djenkins.metrics.prometheus.defaultNamespace=jenkins -Djenkins.metrics.prometheus.useAuthenticatedEndpoint=false -Djenkins.metrics.prometheus.endpoint=/prometheus
    ports:
      - "8080:8080"
      - "50000:50000"

  prometheus:
    environment:
      - JENKINS_USER=${JENKINS_USER:-admin}
      - JENKINS_TOKEN=${JENKINS_TOKEN:-admin}