apiVersion: 1

contactPoints:
  - name: "email-notifications"
    orgId: 1
    receivers:
      - uid: email_cp
        type: email
        settings:
          addresses: hashmimdniyaz@gmail.com
          singleEmail: false
    
    routes:
      - receiver: email_cp
        group_by: ['alertname']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
        matchers:
          - severity = critical
          - severity = warning