apiVersion: 1

notifiers:
  - name: email-notifications
    type: email
    uid: email_notifier
    org_id: 1
    is_default: true
    settings:
      addresses: hashmimdniyaz@gmail.com
      singleEmail: false
    secureSettings: {}

delete_notifiers: []