name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Prometheus
      run: |
        mkdir -p prometheus
        cp prometheus.yml prometheus/prometheus.yml
        docker run -d \
          --name prometheus \
          -p 9090:9090 \
          -v ${{ github.workspace }}/prometheus:/etc/prometheus \
          prom/prometheus
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm run all:headless
      env:
        METRICS_PORT: 9323
    - name: Verify metrics endpoint
      run: |
        sleep 5  # Give the metrics server time to start
        curl -f http://localhost:9323/metrics || echo "Metrics endpoint not accessible"
        docker logs prometheus
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: my-report/
        retention-days: 7
